apiVersion: v1
kind: ConfigMap
metadata:
  name: piggymetrics-config
  namespace: piggymetricss
data:
  CONFIG_SERVICE_PASSWORD: "password"
  NOTIFICATION_SERVICE_PASSWORD: "password"
  STATISTICS_SERVICE_PASSWORD: "password"
  ACCOUNT_SERVICE_PASSWORD: "password"
  MONGODB_PASSWORD: "password"